#!/usr/bin/ksh

/etc/profile
. /u/vraadmin/.profile < /vradfo/prod/control/reffile/modefile

THIS_TIMESTAMP="T`date +"%Y%m%d%H%M%S"`"
THIS_PROCESS_NO="_P$$"

export SCHEMA="vrap"
export HOME_DIR="/vradfo/prod"
export FTP_STAGING_DIR="/vradfo/dfoftp"
export TEMP_DIR="$HOME_DIR/temp/$THIS_TIMESTAMP$THIS_PROCESS_NO"
export DATA_FILE_NAME_FILE="$TEMP_DIR/data_file_name_file"
export SCRIPT_DIR="$HOME_DIR/script"
export EXE_DIR="$HOME_DIR/exe"
export STAGING_DIR="$HOME_DIR/staging"
export TEMP_DATA_DIR="$TEMP_DIR/dat"
export LOG_DIR="$HOME_DIR/log"

mkdir -p $TEMP_DATA_DIR

export MASTER_LOG="$LOG_DIR/DFO_master.log"
export LOG_FILE="$LOG_DIR/DFO_$CLIENT_NAME$THIS_PROCESS_NO.log"
export REF_DIR="$HOME_DIR/control/reffile"
export DATA_LOAD_DIR="$HOME_DIR/control/dataload"
export DBA_DATA_LOAD_DIR="/vradfo/prodload"
export MAIL_SUBJECT=""
export SUPPORT_MAIL_LIST_FILE="$REF_DIR/DFO_support_maillist.ref"
export CONTRACT_ADMIN_MAIL_LIST_FILE="$REF_DIR/DFO_contract_admin_maillist.ref"
export MAILFILE="$TEMP_DIR/mailfile"
export MAIL_BODY_FILE
export TWO_PERCENT_MAIL_BODY="$REF_DIR/DFO_two_percent_mail_body.ref"
export INVALID_FILE_MAIL_BODY="$REF_DIR/DFO_invalid_file_mail_body.ref"
export INVALID_FILENAME_MAIL_BODY="$REF_DIR/DFO_invalid_filename_mail_body.ref"

export CONTRACT_FILE="$TEMP_DATA_DIR/DFO_client_contract_info.ref"
export ERROR_DESC_FILE="$REF_DIR/DFO_error_desc_index.ref"

export PROCESS_MONTH_PARM_FILE="$TEMP_DATA_DIR/DFO_process_month_parm.ref"

export CLIENT_DIR="$HOME_DIR/clients/$CLIENT_NAME"
export PROCESSED_DIR="$CLIENT_DIR/processed"
export FAILED_DIR="$CLIENT_DIR/failed"
export CONTRACT_AUDIT_FILE="$HOME_DIR/clients/contract_audit_file"
export PROCESSOR_NO_FILE="$TEMP_DIR/processor_no_file"
